# Generated by Django 4.0.4 on 2022-07-14 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_registeruser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(max_length=100)),
                ('publish_Date', models.CharField(max_length=12)),
                ('auther_name', models.CharField(max_length=20)),
                ('blog_content', models.TextField()),
            ],
        ),
    ]
